In [1]:
import numpy as np
import pandas as pd
import xarray as xr
import os

In [25]:
#Archivo .grib que deseamos leer
file = 'apcp_sfc_2013031600_c00.grib2'

#Carpeta donde se encuentra el archivo
folder = '/home/fernando.huaranca/test_forecast'

#Ruta del archivo
path = os.path.join(folder,file)
print(path)

##########

#Tiempos de interes 
#times_forecast = [1,3,5,7]

ds = xr.open_dataset(path)

/home/fernando.huaranca/test_forecast/apcp_sfc_2013031600_c00.grib2


In [4]:
def find_desired_hour_indices(steps, desired_hours):
    # Convertir los pasos a un objeto Series de pandas para trabajar con fechas
    steps_series = pd.Series(steps.values)

    # Obtener la hora de cada paso
    horas = steps_series.dt.components.hours

    # Encontrar los índices donde se encuentran las horas deseadas
    desired_indices = [idx for idx, hora in enumerate(horas) if hora in desired_hours]

    return desired_indices

# Horas deseadas: 00, 06, 12 y 18 UTC
desired_hours = [0, 6, 12, 18]

# Obtener los índices de las horas deseadas
desired_indices = find_desired_hour_indices(ds.step, desired_hours)



# Imprimir los índices de las horas deseadas
print(desired_indices)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79]


In [13]:
#Vamos paso por paso
fechas = pd.Series(ds.time.values+ds.step.values)
horas_interes = [0,6,12,18]
fechas

Timestamp('2013-03-16 03:00:00')

In [17]:
.hour == 6

SyntaxError: invalid syntax (347230409.py, line 1)

In [18]:
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]
posiciones = [fechas_series.index[fechas_series.dt.hour == hora] for hora in horas_interes]

# Imprime las posiciones encontradas
for i, hora in enumerate(horas_interes):
    print(f"Posiciones para la hora {hora} UTC:")
    print(posiciones[i])
    print("-------------------")

# Cierra el archivo
ds.close()


Posiciones para la hora 0 UTC:
Index([7, 15, 23, 31, 39, 47, 55, 63, 71, 79], dtype='int64')
-------------------
Posiciones para la hora 6 UTC:
Index([1, 9, 17, 25, 33, 41, 49, 57, 65, 73], dtype='int64')
-------------------
Posiciones para la hora 12 UTC:
Index([3, 11, 19, 27, 35, 43, 51, 59, 67, 75], dtype='int64')
-------------------
Posiciones para la hora 18 UTC:
Index([5, 13, 21, 29, 37, 45, 53, 61, 69, 77], dtype='int64')
-------------------


In [20]:
posiciones

[Index([7, 15, 23, 31, 39, 47, 55, 63, 71, 79], dtype='int64'),
 Index([1, 9, 17, 25, 33, 41, 49, 57, 65, 73], dtype='int64'),
 Index([3, 11, 19, 27, 35, 43, 51, 59, 67, 75], dtype='int64'),
 Index([5, 13, 21, 29, 37, 45, 53, 61, 69, 77], dtype='int64')]

In [21]:
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea un diccionario para almacenar las posiciones de cada día
posiciones_por_dia = {hora: [] for hora in horas_interes}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    for hora in horas_interes:
        posiciones = fechas_series.index[(fechas_series.dt.date == fecha) & (fechas_series.dt.hour == hora)]
        posiciones_por_dia[hora].append(posiciones)

# Imprime las posiciones por día para cada hora de interés
for hora, posiciones_dia in posiciones_por_dia.items():
    print(f"Posiciones para la hora {hora} UTC:")
    for i, posiciones in enumerate(posiciones_dia):
        print(f"Día {i+1}: {posiciones}")
    print("-------------------")



Posiciones para la hora 0 UTC:
Día 1: Index([], dtype='int64')
Día 2: Index([7], dtype='int64')
Día 3: Index([15], dtype='int64')
Día 4: Index([23], dtype='int64')
Día 5: Index([31], dtype='int64')
Día 6: Index([39], dtype='int64')
Día 7: Index([47], dtype='int64')
Día 8: Index([55], dtype='int64')
Día 9: Index([63], dtype='int64')
Día 10: Index([71], dtype='int64')
Día 11: Index([79], dtype='int64')
-------------------
Posiciones para la hora 6 UTC:
Día 1: Index([1], dtype='int64')
Día 2: Index([9], dtype='int64')
Día 3: Index([17], dtype='int64')
Día 4: Index([25], dtype='int64')
Día 5: Index([33], dtype='int64')
Día 6: Index([41], dtype='int64')
Día 7: Index([49], dtype='int64')
Día 8: Index([57], dtype='int64')
Día 9: Index([65], dtype='int64')
Día 10: Index([73], dtype='int64')
Día 11: Index([], dtype='int64')
-------------------
Posiciones para la hora 12 UTC:
Día 1: Index([3], dtype='int64')
Día 2: Index([11], dtype='int64')
Día 3: Index([19], dtype='int64')
Día 4: Index([27], d

In [22]:

fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea un diccionario para almacenar las posiciones por día y hora
posiciones_por_dia_hora = {}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    for hora in horas_interes:
        posiciones = fechas_series.index[(fechas_series.dt.date == fecha) & (fechas_series.dt.hour == hora)]
        if posiciones.size > 0:
            fecha_str = fecha.strftime('%d-%m-%Y')
            if fecha_str not in posiciones_por_dia_hora:
                posiciones_por_dia_hora[fecha_str] = {hora: posiciones}
            else:
                posiciones_por_dia_hora[fecha_str][hora] = posiciones

# Imprime las fechas y posiciones por día y hora
for fecha, horas_posiciones in posiciones_por_dia_hora.items():
    print(f"Fecha {fecha}:")
    for hora, posiciones in horas_posiciones.items():
        print(f"Hora {hora} UTC: {posiciones}")
    print("-------------------")




Fecha 16-03-2013:
Hora 6 UTC: Index([1], dtype='int64')
Hora 12 UTC: Index([3], dtype='int64')
Hora 18 UTC: Index([5], dtype='int64')
-------------------
Fecha 17-03-2013:
Hora 0 UTC: Index([7], dtype='int64')
Hora 6 UTC: Index([9], dtype='int64')
Hora 12 UTC: Index([11], dtype='int64')
Hora 18 UTC: Index([13], dtype='int64')
-------------------
Fecha 18-03-2013:
Hora 0 UTC: Index([15], dtype='int64')
Hora 6 UTC: Index([17], dtype='int64')
Hora 12 UTC: Index([19], dtype='int64')
Hora 18 UTC: Index([21], dtype='int64')
-------------------
Fecha 19-03-2013:
Hora 0 UTC: Index([23], dtype='int64')
Hora 6 UTC: Index([25], dtype='int64')
Hora 12 UTC: Index([27], dtype='int64')
Hora 18 UTC: Index([29], dtype='int64')
-------------------
Fecha 20-03-2013:
Hora 0 UTC: Index([31], dtype='int64')
Hora 6 UTC: Index([33], dtype='int64')
Hora 12 UTC: Index([35], dtype='int64')
Hora 18 UTC: Index([37], dtype='int64')
-------------------
Fecha 21-03-2013:
Hora 0 UTC: Index([39], dtype='int64')
Hora 6 

In [ ]:
import pandas as pd
import xarray as xr

# Abre el archivo y carga los datos relevantes
ds = xr.open_dataset('ruta/a/tu/archivo.grib2')
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea un diccionario para almacenar las posiciones por día y hora
posiciones_por_dia_hora = {}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    posiciones_por_dia_hora[fecha.strftime('%d-%m-%Y')] = {hora: [] for hora in horas_interes}

for idx, fecha_hora in fechas_series.iteritems():
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_dia_hora[fecha_str][hora].append(idx)

# Imprime las fechas y posiciones por día y hora
for fecha, horas_posiciones in pos


In [26]:

fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea un diccionario para almacenar las posiciones por día y hora
posiciones_por_dia_hora = {}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    posiciones_por_dia_hora[fecha.strftime('%d-%m-%Y')] = {hora: [] for hora in horas_interes}

for idx, fecha_hora in fechas_series.iteritems():
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_dia_hora[fecha_str][hora].append(idx)

# Imprime las fechas y posiciones por día y hora
for fecha, horas_posiciones in posiciones_por_dia_hora.items():
    print(f"Fecha {fecha}:")
    for hora, posiciones in horas_posiciones.items():
        print(f"Hora {hora} UTC: {posiciones}")
    print("-------------------")



AttributeError: 'Series' object has no attribute 'iteritems'

In [28]:

fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [6,12,18,0]

# Crea un diccionario para almacenar las posiciones por día y hora
posiciones_por_dia_hora = {}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    posiciones_por_dia_hora[fecha.strftime('%d-%m-%Y')] = {hora: [] for hora in horas_interes}

for idx, fecha_hora in fechas_series.items():
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_dia_hora[fecha_str][hora].append(idx)

# Imprime las fechas y posiciones por día y hora
for fecha, horas_posiciones in posiciones_por_dia_hora.items():
    print(f"Fecha {fecha}:")
    for hora, posiciones in horas_posiciones.items():
        print(f"Hora {hora} UTC: {posiciones}")
    print("-------------------")



Fecha 16-03-2013:
Hora 6 UTC: [1]
Hora 12 UTC: [3]
Hora 18 UTC: [5]
Hora 0 UTC: []
-------------------
Fecha 17-03-2013:
Hora 6 UTC: [9]
Hora 12 UTC: [11]
Hora 18 UTC: [13]
Hora 0 UTC: [7]
-------------------
Fecha 18-03-2013:
Hora 6 UTC: [17]
Hora 12 UTC: [19]
Hora 18 UTC: [21]
Hora 0 UTC: [15]
-------------------
Fecha 19-03-2013:
Hora 6 UTC: [25]
Hora 12 UTC: [27]
Hora 18 UTC: [29]
Hora 0 UTC: [23]
-------------------
Fecha 20-03-2013:
Hora 6 UTC: [33]
Hora 12 UTC: [35]
Hora 18 UTC: [37]
Hora 0 UTC: [31]
-------------------
Fecha 21-03-2013:
Hora 6 UTC: [41]
Hora 12 UTC: [43]
Hora 18 UTC: [45]
Hora 0 UTC: [39]
-------------------
Fecha 22-03-2013:
Hora 6 UTC: [49]
Hora 12 UTC: [51]
Hora 18 UTC: [53]
Hora 0 UTC: [47]
-------------------
Fecha 23-03-2013:
Hora 6 UTC: [57]
Hora 12 UTC: [59]
Hora 18 UTC: [61]
Hora 0 UTC: [55]
-------------------
Fecha 24-03-2013:
Hora 6 UTC: [65]
Hora 12 UTC: [67]
Hora 18 UTC: [69]
Hora 0 UTC: [63]
-------------------
Fecha 25-03-2013:
Hora 6 UTC: [73]


In [29]:
###El codigo que mejor salio
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea un diccionario para almacenar las posiciones por día y hora
posiciones_por_dia_hora = {}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    posiciones_por_dia_hora[fecha.strftime('%d-%m-%Y')] = {hora: [] for hora in horas_interes}

for idx, fecha_hora in fechas_series.items():
    fecha_hora = fecha_hora - pd.Timedelta(hours=6)  # Resta 6 horas para ajustar al día anterior
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_dia_hora[fecha_str][hora].append(idx)

# Imprime las fechas y posiciones por día y hora
for fecha, horas_posiciones in posiciones_por_dia_hora.items():
    print(f"Fecha {fecha}:")
    for hora, posiciones in horas_posiciones.items():
        print(f"Hora {hora} UTC: {posiciones}")
    print("-------------------")



Fecha 16-03-2013:
Hora 0 UTC: [1]
Hora 6 UTC: [3]
Hora 12 UTC: [5]
Hora 18 UTC: [7]
-------------------
Fecha 17-03-2013:
Hora 0 UTC: [9]
Hora 6 UTC: [11]
Hora 12 UTC: [13]
Hora 18 UTC: [15]
-------------------
Fecha 18-03-2013:
Hora 0 UTC: [17]
Hora 6 UTC: [19]
Hora 12 UTC: [21]
Hora 18 UTC: [23]
-------------------
Fecha 19-03-2013:
Hora 0 UTC: [25]
Hora 6 UTC: [27]
Hora 12 UTC: [29]
Hora 18 UTC: [31]
-------------------
Fecha 20-03-2013:
Hora 0 UTC: [33]
Hora 6 UTC: [35]
Hora 12 UTC: [37]
Hora 18 UTC: [39]
-------------------
Fecha 21-03-2013:
Hora 0 UTC: [41]
Hora 6 UTC: [43]
Hora 12 UTC: [45]
Hora 18 UTC: [47]
-------------------
Fecha 22-03-2013:
Hora 0 UTC: [49]
Hora 6 UTC: [51]
Hora 12 UTC: [53]
Hora 18 UTC: [55]
-------------------
Fecha 23-03-2013:
Hora 0 UTC: [57]
Hora 6 UTC: [59]
Hora 12 UTC: [61]
Hora 18 UTC: [63]
-------------------
Fecha 24-03-2013:
Hora 0 UTC: [65]
Hora 6 UTC: [67]
Hora 12 UTC: [69]
Hora 18 UTC: [71]
-------------------
Fecha 25-03-2013:
Hora 0 UTC: [73

In [30]:
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea un diccionario para almacenar las posiciones por día y hora
posiciones_por_dia_hora = {}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    posiciones_por_dia_hora[fecha.strftime('%d-%m-%Y')] = {hora: [] for hora in horas_interes}

for idx, fecha_hora in fechas_series.items():
    fecha_hora = fecha_hora - pd.Timedelta(hours=6)  # Resta 6 horas para ajustar al día anterior
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_dia_hora[fecha_str][hora].append(idx)

# Crear la matriz de resultados
matriz_resultados = np.zeros((len(posiciones_por_dia_hora), len(horas_interes)), dtype=int)

# Llenar la matriz con las posiciones
for i, (fecha, horas_posiciones) in enumerate(posiciones_por_dia_hora.items()):
    for j, hora in enumerate(horas_interes):
        matriz_resultados[i, j] = len(horas_posiciones[hora])

# Imprime la matriz de resultados
print("Matriz de resultados:")
print(matriz_resultados)




Matriz de resultados:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]


In [31]:
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crear una matriz para almacenar las posiciones
matriz_posiciones = np.empty((len(fechas_series), len(horas_interes)), dtype=object)
matriz_posiciones[:] = None  # Inicializar con None

# Llenar la matriz con las posiciones
for idx, fecha_hora in fechas_series.items():
    fecha_hora = fecha_hora - pd.Timedelta(hours=6)  # Resta 6 horas para ajustar al día anterior
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        matriz_posiciones[idx, horas_interes.index(hora)] = idx

# Imprimir la matriz de posiciones
for i, fecha_hora in enumerate(fechas_series):
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    print(f"Fecha {fecha_str}:")
    for j, hora in enumerate(horas_interes):
        print(f"Hora {hora} UTC:", matriz_posiciones[i, j])
    print("-------------------")

# Cierra el archivo
ds.close()


Fecha 16-03-2013:
Hora 0 UTC: None
Hora 6 UTC: None
Hora 12 UTC: None
Hora 18 UTC: None
-------------------
Fecha 16-03-2013:
Hora 0 UTC: 1
Hora 6 UTC: None
Hora 12 UTC: None
Hora 18 UTC: None
-------------------
Fecha 16-03-2013:
Hora 0 UTC: None
Hora 6 UTC: None
Hora 12 UTC: None
Hora 18 UTC: None
-------------------
Fecha 16-03-2013:
Hora 0 UTC: None
Hora 6 UTC: 3
Hora 12 UTC: None
Hora 18 UTC: None
-------------------
Fecha 16-03-2013:
Hora 0 UTC: None
Hora 6 UTC: None
Hora 12 UTC: None
Hora 18 UTC: None
-------------------
Fecha 16-03-2013:
Hora 0 UTC: None
Hora 6 UTC: None
Hora 12 UTC: 5
Hora 18 UTC: None
-------------------
Fecha 16-03-2013:
Hora 0 UTC: None
Hora 6 UTC: None
Hora 12 UTC: None
Hora 18 UTC: None
-------------------
Fecha 17-03-2013:
Hora 0 UTC: None
Hora 6 UTC: None
Hora 12 UTC: None
Hora 18 UTC: 7
-------------------
Fecha 17-03-2013:
Hora 0 UTC: None
Hora 6 UTC: None
Hora 12 UTC: None
Hora 18 UTC: None
-------------------
Fecha 17-03-2013:
Hora 0 UTC: 9
Hora 6 U

In [33]:
matriz_posiciones[1,:]

array([1, None, None, None], dtype=object)

## Este es el codigo que tenes que adaptar para una matriz

In [53]:
###El codigo que mejor salio
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea un diccionario para almacenar las posiciones por día y hora
posiciones_por_dia_hora = {}

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    posiciones_por_dia_hora[fecha.strftime('%d-%m-%Y')] = {hora: [] for hora in horas_interes}

for idx, fecha_hora in fechas_series.items():
    fecha_hora = fecha_hora - pd.Timedelta(hours=6)  # Resta 6 horas para ajustar al día anterior
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_dia_hora[fecha_str][hora].append(idx)

posiciones_por_dia_hora

{'16-03-2013': {0: [1], 6: [3], 12: [5], 18: [7]},
 '17-03-2013': {0: [9], 6: [11], 12: [13], 18: [15]},
 '18-03-2013': {0: [17], 6: [19], 12: [21], 18: [23]},
 '19-03-2013': {0: [25], 6: [27], 12: [29], 18: [31]},
 '20-03-2013': {0: [33], 6: [35], 12: [37], 18: [39]},
 '21-03-2013': {0: [41], 6: [43], 12: [45], 18: [47]},
 '22-03-2013': {0: [49], 6: [51], 12: [53], 18: [55]},
 '23-03-2013': {0: [57], 6: [59], 12: [61], 18: [63]},
 '24-03-2013': {0: [65], 6: [67], 12: [69], 18: [71]},
 '25-03-2013': {0: [73], 6: [75], 12: [77], 18: [79]},
 '26-03-2013': {0: [], 6: [], 12: [], 18: []}}

In [57]:
posiciones_por_dia_hora.values

<function dict.values>

In [ ]:
###El codigo que mejor salio
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crea una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crea una matriz para almacenar las posiciones por día y hora
matriz_total = np.zeros([ds.step.shape[0],4])

# Itera a través de las fechas y agrega las posiciones al diccionario
for fecha in fechas_series.dt.date.unique():
    matriz_total= {hora: [] for hora in horas_interes}

#

In [48]:
for fecha in fechas_series.dt.date.unique():
    posiciones_por_dia_hora[fecha.strftime('%d-%m-%Y')] = {hora: [] for hora in horas_interes}

In [79]:
int(ds.step.shape[0]/8)

10

In [80]:
# Crear un arreglo con las fechas y horas
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crear una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

###### Crear un array para almacenar las posiciones por día y hora#####

n_col = 4 # 06 12 18 00utc

#ya que son la cantidad de step dividido por la cantidad de tiempos por dia
n_row = int(ds.step.shape[0]/8) 

posiciones_por_dia_hora = np.zeros((n_row, n_col), dtype=object)

# Inicializar índices para el array
indice_fila = 0
indice_columna = 0

# Iterar a través de las fechas y agregar las posiciones al array
for idx, fecha_hora in fechas_series.items():
    fecha_hora = fecha_hora - pd.Timedelta(hours=6)  # Resta 6 horas para ajustar al día anterior
    fecha_str = fecha_hora.strftime('%d-%m-%Y')
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_dia_hora[indice_fila, indice_columna] = idx
        indice_columna += 1
        if indice_columna == 4:
            indice_columna = 0
            indice_fila += 1
print(posiciones_por_dia_hora)


[[1 3 5 7]
 [9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]
 [41 43 45 47]
 [49 51 53 55]
 [57 59 61 63]
 [65 67 69 71]
 [73 75 77 79]]


In [62]:
posiciones_por_dia_hora[0,:]

array([1, 3, 5, 7], dtype=object)

In [59]:
# Crear un arreglo con las fechas y horas
fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crear una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crear una lista para almacenar las posiciones de cada hora
posiciones_por_hora = []

# Iterar a través de las fechas y agregar las posiciones a la lista
for idx, fecha_hora in fechas_series.items():
    fecha_hora = fecha_hora - pd.Timedelta(hours=6)  # Resta 6 horas para ajustar al día anterior
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_hora.append(idx)

# Convertir la lista en un array numpy
posiciones_array = np.array(posiciones_por_hora)

# Imprimir el array con las posiciones
print(posiciones_array)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79]


In [60]:

fechas_horas = pd.to_datetime(ds.time.values + ds.step.values, origin='unix', unit='ns')

# Crear una Serie con las fechas y horas
fechas_series = pd.Series(fechas_horas)

# Encuentra las posiciones de las horas 00, 06, 12 y 18
horas_interes = [0, 6, 12, 18]

# Crear una lista para almacenar las posiciones de cada hora
posiciones_por_hora = []

# Iterar a través de las fechas y agregar las posiciones a la lista
for idx, fecha_hora in fechas_series.items():
    fecha_hora = fecha_hora - pd.Timedelta(hours=6)  # Resta 6 horas para ajustar al día anterior
    hora = fecha_hora.hour
    if hora in horas_interes:
        posiciones_por_hora.append(idx)

# Crear una matriz de 20x4 con valores -1
matriz_posiciones = np.full((20, 4), -1)

# Llenar la matriz con las posiciones correspondientes
for i, idx in enumerate(posiciones_por_hora):
    dia = i // 4  # Fila en la matriz
    hora = i % 4  # Columna en la matriz
    matriz_posiciones[dia, hora] = idx

# Imprimir la matriz
print(matriz_posiciones)


[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]
 [41 43 45 47]
 [49 51 53 55]
 [57 59 61 63]
 [65 67 69 71]
 [73 75 77 79]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
